// 20 Government Welfare Schemes for JanSaathi
export const schemes = [
  {
    schemeId: 'pm-kisan',
    name: 'PM-KISAN',
    nameHindi: 'प्रधानमंत्री किसान सम्मान निधि',
    description: 'Direct income support of ₹6,000 per year to farmer families owning cultivable land',
    benefits: ['₹2,000 paid every 4 months', 'Direct bank transfer', 'No application fee'],
    eligibility: {
      occupations: ['farmer', 'agriculture'],
      states: [], // All India
    },
    applicationProcess: 'Register on PM-KISAN portal with Aadhaar and land records',
    officialWebsite: 'https://pmkisan.gov.in',
    category: 'Agriculture',
    benefitAmount: 6000,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'pm-awas-yojana',
    name: 'PM Awas Yojana Gramin',
    nameHindi: 'प्रधानमंत्री आवास योजना ग्रामीण',
    description: 'Financial assistance of ₹1,20,000 for construction of pucca house in rural areas',
    benefits: ['₹1,20,000 for house construction', 'Toilet construction support', 'Piped water connection'],
    eligibility: {
      bplRequired: true,
      states: [],
    },
    applicationProcess: 'Apply through Gram Panchayat or online portal',
    officialWebsite: 'https://pmayg.nic.in',
    category: 'Housing',
    benefitAmount: 120000,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'ujjwala-yojana',
    name: 'Pradhan Mantri Ujjwala Yojana',
    nameHindi: 'प्रधानमंत्री उज्ज्वला योजना',
    description: 'Free LPG connection to women from BPL households',
    benefits: ['Free LPG connection', '₹1,600 support for connection', 'First refill support'],
    eligibility: {
      target_gender: 'female',
      bplRequired: true,
      states: [],
    },
    applicationProcess: 'Apply at nearest LPG distributor with BPL card',
    officialWebsite: 'https://www.pmuy.gov.in',
    category: 'Energy',
    benefitAmount: 1600,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'ayushman-bharat',
    name: 'Ayushman Bharat PM-JAY',
    nameHindi: 'आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना',
    description: 'Health insurance cover of ₹5 lakh per family per year for secondary and tertiary care',
    benefits: ['₹5 lakh health cover', 'Cashless treatment', 'Pre and post hospitalization'],
    eligibility: {
      bplRequired: true,
      states: [],
    },
    applicationProcess: 'Check eligibility and get Ayushman card from nearest center',
    officialWebsite: 'https://pmjay.gov.in',
    category: 'Health',
    benefitAmount: 500000,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'pm-fasal-bima',
    name: 'PM Fasal Bima Yojana',
    nameHindi: 'प्रधानमंत्री फसल बीमा योजना',
    description: 'Crop insurance scheme providing financial support to farmers in case of crop failure',
    benefits: ['Up to ₹2,00,000 insurance', 'Low premium (2% for Kharif)', 'Quick claim settlement'],
    eligibility: {
      occupations: ['farmer', 'agriculture'],
      states: [],
    },
    applicationProcess: 'Apply through bank or Common Service Centers before sowing',
    officialWebsite: 'https://pmfby.gov.in',
    category: 'Agriculture',
    benefitAmount: 200000,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'kisan-credit-card',
    name: 'Kisan Credit Card',
    nameHindi: 'किसान क्रेडिट कार्ड',
    description: 'Credit facility up to ₹3 lakh for farmers at subsidized interest rates',
    benefits: ['Up to ₹3 lakh credit', '4% interest rate', 'Flexible repayment'],
    eligibility: {
      occupations: ['farmer', 'agriculture'],
      states: [],
    },
    applicationProcess: 'Apply at nearest bank branch with land documents',
    officialWebsite: 'https://www.nabard.org/kcc.aspx',
    category: 'Agriculture',
    benefitAmount: 300000,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'nsp-sc-scholarship',
    name: 'NSP Post-Matric Scholarship SC',
    nameHindi: 'एनएसपी पोस्ट मैट्रिक छात्रवृत्ति अनुसूचित जाति',
    description: 'Scholarship for SC students pursuing post-matriculation studies',
    benefits: ['Up to ₹25,000 per year', 'Tuition fee reimbursement', 'Maintenance allowance'],
    eligibility: {
      occupations: ['student'],
      caste: ['SC'],
      ageMin: 16,
      ageMax: 30,
      states: [],
    },
    applicationProcess: 'Apply online on National Scholarship Portal',
    officialWebsite: 'https://scholarships.gov.in',
    category: 'Education',
    benefitAmount: 25000,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'nsp-st-scholarship',
    name: 'NSP Post-Matric Scholarship ST',
    nameHindi: 'एनएसपी पोस्ट मैट्रिक छात्रवृत्ति अनुसूचित जनजाति',
    description: 'Scholarship for ST students pursuing post-matriculation studies',
    benefits: ['Up to ₹25,000 per year', 'Tuition fee reimbursement', 'Maintenance allowance'],
    eligibility: {
      occupations: ['student'],
      caste: ['ST'],
      ageMin: 16,
      ageMax: 30,
      states: [],
    },
    applicationProcess: 'Apply online on National Scholarship Portal',
    officialWebsite: 'https://scholarships.gov.in',
    category: 'Education',
    benefitAmount: 25000,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'nsp-obc-scholarship',
    name: 'NSP Pre-Matric Scholarship OBC',
    nameHindi: 'एनएसपी प्री मैट्रिक छात्रवृत्ति अन्य पिछड़ा वर्ग',
    description: 'Scholarship for OBC students in classes 9 and 10',
    benefits: ['Up to ₹10,000 per year', 'Books and stationery allowance', 'No income limit'],
    eligibility: {
      occupations: ['student'],
      caste: ['OBC'],
      ageMin: 14,
      ageMax: 18,
      states: [],
    },
    applicationProcess: 'Apply online on National Scholarship Portal',
    officialWebsite: 'https://scholarships.gov.in',
    category: 'Education',
    benefitAmount: 10000,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'mgnrega',
    name: 'MGNREGA',
    nameHindi: 'महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम',
    description: 'Guaranteed 100 days of wage employment per year to rural households',
    benefits: ['₹250 per day wage', '100 days guaranteed work', 'Payment within 15 days'],
    eligibility: {
      occupations: ['daily_wage', 'unemployed'],
      states: [],
    },
    applicationProcess: 'Register at Gram Panchayat with job card',
    officialWebsite: 'https://nrega.nic.in',
    category: 'Social',
    benefitAmount: 25000,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'pm-mudra-yojana',
    name: 'Pradhan Mantri Mudra Yojana',
    nameHindi: 'प्रधानमंत्री मुद्रा योजना',
    description: 'Collateral-free loans up to ₹10 lakh for small businesses',
    benefits: ['Up to ₹10 lakh loan', 'No collateral required', 'Low interest rates'],
    eligibility: {
      occupations: ['small_business', 'self_employed'],
      states: [],
    },
    applicationProcess: 'Apply at nearest bank or NBFC with business plan',
    officialWebsite: 'https://www.mudra.org.in',
    category: 'Financial',
    benefitAmount: 1000000,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'atal-pension-yojana',
    name: 'Atal Pension Yojana',
    nameHindi: 'अटल पेंशन योजना',
    description: 'Pension scheme for unorganized sector workers with guaranteed monthly pension',
    benefits: ['₹1,000 to ₹5,000 monthly pension', 'Government co-contribution', 'Nominee benefits'],
    eligibility: {
      ageMin: 18,
      ageMax: 40,
      states: [],
    },
    applicationProcess: 'Open account at any bank with Aadhaar',
    officialWebsite: 'https://npscra.nsdl.co.in/apy',
    category: 'Social',
    benefitAmount: 60000,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'pm-suraksha-bima',
    name: 'PM Suraksha Bima Yojana',
    nameHindi: 'प्रधानमंत्री सुरक्षा बीमा योजना',
    description: 'Accident insurance cover of ₹2 lakh at ₹12 per year premium',
    benefits: ['₹2 lakh accident cover', 'Only ₹12 annual premium', 'Easy enrollment'],
    eligibility: {
      ageMin: 18,
      ageMax: 70,
      states: [],
    },
    applicationProcess: 'Enroll through bank account with auto-debit',
    officialWebsite: 'https://www.jansuraksha.gov.in',
    category: 'Financial',
    benefitAmount: 200000,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'pm-jeevan-jyoti',
    name: 'PM Jeevan Jyoti Bima Yojana',
    nameHindi: 'प्रधानमंत्री जीवन ज्योति बीमा योजना',
    description: 'Life insurance cover of ₹2 lakh at ₹330 per year premium',
    benefits: ['₹2 lakh life cover', 'Only ₹330 annual premium', 'Renewable yearly'],
    eligibility: {
      ageMin: 18,
      ageMax: 50,
      states: [],
    },
    applicationProcess: 'Enroll through bank account with auto-debit',
    officialWebsite: 'https://www.jansuraksha.gov.in',
    category: 'Financial',
    benefitAmount: 200000,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'sukanya-samriddhi',
    name: 'Sukanya Samriddhi Yojana',
    nameHindi: 'सुकन्या समृद्धि योजना',
    description: 'Savings scheme for girl child with high interest rate and tax benefits',
    benefits: ['7.6% interest rate', 'Tax benefits under 80C', 'Maturity at 21 years'],
    eligibility: {
      target_gender: 'female',
      ageMin: 0,
      ageMax: 10,
      states: [],
    },
    applicationProcess: 'Open account at post office or authorized bank',
    officialWebsite: 'https://www.nsiindia.gov.in',
    category: 'Social',
    benefitAmount: 0,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'pm-capf-scholarship',
    name: 'PM Scholarship for Central Armed Police Forces',
    nameHindi: 'प्रधानमंत्री छात्रवृत्ति योजना केंद्रीय सशस्त्र पुलिस बल',
    description: 'Scholarship for wards/widows of CAPF and Assam Rifles personnel',
    benefits: ['₹36,000 per year', 'For professional courses', 'Merit-based selection'],
    eligibility: {
      occupations: ['student'],
      ageMin: 18,
      ageMax: 25,
      states: [],
    },
    applicationProcess: 'Apply online on National Scholarship Portal',
    officialWebsite: 'https://scholarships.gov.in',
    category: 'Education',
    benefitAmount: 36000,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'startup-india-seed',
    name: 'Startup India Seed Fund',
    nameHindi: 'स्टार्टअप इंडिया सीड फंड',
    description: 'Financial assistance up to ₹20 lakh for startups at early stage',
    benefits: ['Up to ₹20 lakh funding', 'Proof of concept support', 'Product development'],
    eligibility: {
      occupations: ['entrepreneur', 'self_employed'],
      ageMin: 18,
      states: [],
    },
    applicationProcess: 'Apply online on Startup India portal',
    officialWebsite: 'https://www.startupindia.gov.in',
    category: 'Financial',
    benefitAmount: 2000000,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'stand-up-india',
    name: 'Stand-Up India',
    nameHindi: 'स्टैंड-अप इंडिया',
    description: 'Bank loans between ₹10 lakh to ₹1 crore for SC/ST/Women entrepreneurs',
    benefits: ['₹10L to ₹1Cr loan', 'For greenfield enterprises', '7-year repayment'],
    eligibility: {
      occupations: ['entrepreneur', 'self_employed'],
      caste: ['SC', 'ST'],
      target_gender: 'female',
      ageMin: 18,
      states: [],
    },
    applicationProcess: 'Apply through bank with business plan',
    officialWebsite: 'https://www.standupmitra.in',
    category: 'Financial',
    benefitAmount: 5000000,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'pm-vishwakarma',
    name: 'PM Vishwakarma Yojana',
    nameHindi: 'प्रधानमंत्री विश्वकर्मा योजना',
    description: 'Support for traditional artisans and craftspeople with toolkit and training',
    benefits: ['₹15,000 toolkit support', 'Skill training', 'Credit support up to ₹3 lakh'],
    eligibility: {
      occupations: ['artisan', 'craftsperson', 'self_employed'],
      ageMin: 18,
      states: [],
    },
    applicationProcess: 'Register on PM Vishwakarma portal',
    officialWebsite: 'https://pmvishwakarma.gov.in',
    category: 'Social',
    benefitAmount: 315000,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
  {
    schemeId: 'anganwadi-services',
    name: 'Anganwadi Services',
    nameHindi: 'आंगनवाड़ी सेवाएं',
    description: 'Nutrition, preschool education, and health services for children under 6 and pregnant women',
    benefits: ['Supplementary nutrition', 'Preschool education', 'Health checkups', 'Immunization'],
    eligibility: {
      ageMin: 0,
      ageMax: 6,
      states: [],
    },
    applicationProcess: 'Register at nearest Anganwadi center',
    officialWebsite: 'https://wcd.nic.in',
    category: 'Health',
    benefitAmount: 0,
    lastUpdated: new Date().toISOString(),
    version: 1,
  },
];
